inherit_from:
  - .rubocop_todo.yml
  - .rubocop-todo.yml



AllCops:
  Exclude:
    - "db/schema.rb"
    - "config/puma.rb"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "db/migrate/*.rb"
    - "bin/*"
  DisplayCopNames: true
  TargetRubyVersion: 2.6.5

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# 「and」「or」の使用を許可
AndOr:
  Enabled: false
  
Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  
Style/SymbolArray:
  Enabled: false