version: '3'
services:
  app:
    build:
      context: .
    environment:
      - RAILS_ENV=production
    command: >
      bash -c "bundle exec rails db:migrate &&
      bundle exec rails assets:precompile &&
      bundle exec puma -C config/puma.rb"
    volumes:
      - public-data:myapp/public
      - socket-data:/myapp/tmp/sockets

  web:
    build:
      context: containers/nginx
    volumes:
      - .:/myapp
      - public-data:myapp/public
      - socket-data:/myapp/tmp/sockets
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  public-data:
  socket-data:
